// ────────── YouTube Cookie Manager ──────────

import { BrowserWindow, ipcMain } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import { libraries } from './paths';

const YOUTUBE_LIBS_PATH = path.join(libraries, 'yt-dlp');
const COOKIES_FILE_PATH = path.join(YOUTUBE_LIBS_PATH, 'cookies.txt');

export class YouTubeCookieManager {
  private cookiesPath: string;

  constructor() {
    this.cookiesPath = COOKIES_FILE_PATH;

    if (!fs.existsSync(YOUTUBE_LIBS_PATH)) {
      fs.mkdirSync(YOUTUBE_LIBS_PATH, { recursive: true });
    }
  }

  /**
   * Get the path to the Netscape format cookies file
   */
  getCookiesPath(): string {
    return this.cookiesPath;
  }

  /**
   * Convert Electron cookie to Netscape format line
   */
  private cookieToNetscapeLine(cookie: Electron.Cookie): string {
    const domain = cookie.domain || '.youtube.com';
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiration = cookie.expirationDate
      ? Math.floor(cookie.expirationDate)
      : 0;
    const name = cookie.name;
    const value = cookie.value;

    return `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}`;
  }

  /**
   * Parse Netscape cookie line to get expiry info
   */
  private parseNetscapeLine(line: string): { name: string; expiry: number } | null {
    const parts = line.split('\t');
    if (parts.length < 7) return null;

    return {
      name: parts[5],
      expiry: parseInt(parts[4], 10)
    };
  }

  /**
   * Get cookie status from the Netscape file
   */
  async getCookieStatus(): Promise<{ exists: boolean; expiry: string | null; cookieCount: number }> {
    try {
      if (!fs.existsSync(this.cookiesPath)) {
        return { exists: false, expiry: null, cookieCount: 0 };
      }

      const content = fs.readFileSync(this.cookiesPath, 'utf-8');
      const lines = content.split('\n').filter(line =>
        line.trim() && !line.startsWith('#')
      );

      if (lines.length === 0) {
        console.log('[yt-cookies] No cookies found in file');
        return { exists: false, expiry: null, cookieCount: 0 };
      }

      const sessionCookieNames = ['SAPISID', 'HSID', 'SSID', 'SID', '__Secure-1PSID', '__Secure-3PSID'];
      let latestExpiry: number | null = null;
      let hasSessionCookie = false;

      for (const line of lines) {
        const cookie = this.parseNetscapeLine(line);
        if (cookie && sessionCookieNames.includes(cookie.name)) {
          hasSessionCookie = true;
          if (cookie.expiry > 0) {
            if (!latestExpiry || cookie.expiry > latestExpiry) {
              latestExpiry = cookie.expiry;
            }
          }
        }
      }

      // Check if expired
      const now = Math.floor(Date.now() / 1000);
      if (latestExpiry && latestExpiry < now) {
        console.log('[yt-cookies] Session expired, deleting cookies');
        await this.deleteCookies();
        return { exists: false, expiry: null, cookieCount: 0 };
      }

      return {
        exists: hasSessionCookie,
        expiry: latestExpiry ? new Date(latestExpiry * 1000).toISOString() : null,
        cookieCount: lines.length
      };
    } catch (error) {
      console.error('[yt-cookies] Error checking cookie status:', error);
      return { exists: false, expiry: null, cookieCount: 0 };
    }
  }

  /**
   * Login to YouTube and save cookies in Netscape format
   */
  async loginYouTube(): Promise<{ success: boolean; error?: string }> {
    try {
      console.log('[yt-cookies] Opening YouTube login window...');

      const loginWindow = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
          nodeIntegration: false,
          contextIsolation: true,
          partition: 'persist:youtube-login'
        }
      });

      loginWindow.loadURL('https://accounts.google.com/ServiceLogin?service=youtube');

      return new Promise((resolve) => {
        loginWindow.webContents.on('did-navigate', async (_, url) => {
          if (url.includes('youtube.com')) {
            console.log('[yt-cookies] Login detected, extracting cookies...');

            try {
              const { session } = loginWindow.webContents;
              const electronCookies = await session.cookies.get({ domain: '.youtube.com' });

              // Convert to Netscape format
              const netscapeLines = electronCookies.map(cookie =>
                this.cookieToNetscapeLine(cookie)
              );

              // Write to file with header
              const header = '# Netscape HTTP Cookie File\n# This file is generated by Virtual Karaoke. Do not edit.\n\n';
              const content = header + netscapeLines.join('\n');

              fs.writeFileSync(this.cookiesPath, content, 'utf-8');

              console.log(`[yt-cookies] Saved ${electronCookies.length} cookies to ${this.cookiesPath}`);
              loginWindow.close();
              resolve({ success: true });
            } catch (error: any) {
              console.error('[yt-cookies] Error saving cookies:', error);
              loginWindow.close();
              resolve({ success: false, error: error.message });
            }
          }
        });

        loginWindow.on('closed', () => {
          resolve({ success: false, error: 'Login window closed' });
        });
      });
    } catch (error: any) {
      console.error('[yt-cookies] Login error:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Delete the cookies file
   */
  async deleteCookies(): Promise<{ success: boolean; error?: string }> {
    try {
      if (fs.existsSync(this.cookiesPath)) {
        fs.unlinkSync(this.cookiesPath);
        console.log('[yt-cookies] Cookies file deleted');
      }
      return { success: true };
    } catch (error: any) {
      console.error('[yt-cookies] Error deleting cookies:', error);
      return { success: false, error: error.message };
    }
  }
}

const manager = new YouTubeCookieManager();
export default manager;

export function registerYouTubeCookieHandlers() {
  ipcMain.handle('get-yt-cookie-status', async () => {
    return await manager.getCookieStatus();
  });

  ipcMain.handle('login-youtube', async () => {
    return await manager.loginYouTube();
  });

  ipcMain.handle('delete-yt-cookie', async () => {
    return await manager.deleteCookies();
  });
}
